included:
  - Projects
excluded:
  - Carthage
  - Pods
  - Tuist
  - Tests
  - .githooks
opt_in_rules:
  - empty_count
  - fatal_error_message
  - sorted_first_last
disabled_rules:
  - trailing_whitespace
  - identifier_name
line_length:
  warning: 200
  error: 200
