included:
  - Projects
  - Sources
  - Modules
excluded:
  - Carthage
  - Pods
  - Tests
opt_in_rules:
  - empty_count
  - fatal_error_message
  - sorted_first_last
disabled_rules:
  - trailing_whitespace
  - identifier_name
line_length:
  warning: 120
  error: 200
